### PR TITLE
Homework4

### PR DESCRIPTION
**Pull request by ivanseki**

### CODE REVIEW

**Comment by ivanseki** [comment]
In last PR you told me to rewrite logic of showing crew in `MovieDetailsScreen`, so I did, but made it only for sixth member of crew. Now in app it renders only first two columns (I don't know if it has only 4 members or 5) but it also makes a big spacer between crew and cast. Any idea how to solve that?

**Comment by ivanseki** [comment]
Also in `FavoritesScreen` it doesn't show `MovieCard` image, just the frame and favorite button. Can't figure out why it does that. Any suggestions?

**Comment by ghost** [comment]
@ivanseki 
> In last PR you told me to rewrite logic of showing crew in MovieDetailsScreen, so I did, but made it only for sixth member of crew. Now in app it renders only first two columns (I don't know if it has only 4 members or 5) but it also makes a big spacer between crew and cast. Any idea how to solve that?

This is how we solved it.

```kotlin
@Composable
private fun CrewList(
    crew: List<CrewmanViewState>,
    modifier: Modifier = Modifier,
) {
    val crewToDisplay = crew
        .take(NUMBER_OF_CREW_TO_DISPLAY)
        .chunked(NUMBER_OF_CREW_TO_DISPLAY / 2)
        .let {
            val firstRow = it.firstOrNull() ?: emptyList()
            val secondRow = it.getOrNull(1) ?: emptyList()

            firstRow.mapIndexed { index, crewman ->
                crewman to secondRow.getOrNull(index)
            }
        }

    Row(
        modifier = modifier,
        horizontalArrangement = Arrangement.SpaceAround
    ) {
        crewToDisplay.forEachIndexed { index, crewmanPair ->
            Column(
                Modifier
                    .weight(1f)
                    .padding(horizontal = if (index == 1) 8.dp else 0.dp)
            ) {
                CrewItem(
                    crewItemViewState = CrewItemViewState(name = crewmanPair.first.name, job = crewmanPair.first.job)
                )

                crewmanPair.second?.let {
                    Spacer(Modifier.height(26.dp))
                    CrewItem(
                        crewItemViewState = CrewItemViewState(name = crewmanPair.second!!.name, job = crewmanPair.second!!.job)
                    )
                }
            }
        }
    }
}
```
where the `CrewItem` composable is implemented like this:
```kotlin
@Composable
fun CrewItem(
    crewItemViewState: CrewItemViewState,
    modifier: Modifier = Modifier,
) {
    Column(modifier) {
        Text(
            text = crewItemViewState.name,
            color = Color.Black,
            fontWeight = FontWeight.Bold,
            fontSize = 14.sp,
            maxLines = 1,
            overflow = TextOverflow.Ellipsis,
        )

        Text(
            text = crewItemViewState.job,
            color = Color.Black,
            fontSize = 14.sp,
            maxLines = 1,
            overflow = TextOverflow.Ellipsis,
        )
    }
}
```


> Also in FavoritesScreen it doesn't show MovieCard image, just the frame and favorite button. Can't figure out why it does that. Any suggestions?

It is because you are not sending the entire url to the MovieCard on the FavoritesScreen but only the image suffix. e.g. `/438QXt1E3WJWb3PqNniK0tAE5c1.jpg`.
When you are mapping the data for the favorites screen add the domain prefix to create a whole URL, then it should work as intended.

**Comment by ivanseki** [comment]
@ivan-varga everything fixed and properly working. Can I merge?

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@ivanseki all good, merge ✅

**Pull request merged**
